#!/bin/csh -f
if (-e ../Cgen.java) then
  ../../PA1/lexer $* | ../../PA2/parser $* | java -classpath /usr/class/cs143/cool/lib:../../PA3/:/usr/java/lib/rt.jar Semant $* | java -classpath /usr/class/cs143/cool/lib:..:/usr/java/lib/rt.jar Cgen $*
else
  ../../PA1/lexer $* | ../../PA2/parser $* | ../../PA3/semant $* | ../cgen $*
endif
