#!/bin/csh -f
if (-e ../Semant.java) then
  ../../PA1/lexer $* | ../../PA2/parser $* | java -classpath /usr/class/cs143/cool/lib:..:/usr/java/lib/rt.jar Semant $*
else
../../PA1/lexer $* | ../../PA2/parser $* | ../semant $*
endif
